<?php

namespace MyPoll\Classes;

use DI\Container;
use Mockery as m;
use MyPoll\Classes\Database\RedBeanDB;
use Twig_Environment;
use Twig_Loader_Filesystem;
use PHPUnit_Framework_TestCase;

class UsersTest extends \PHPUnit_Framework_TestCase
{
    protected $extraArrayFull = array(
        array('method' => 'getById', 'return' => array(
            'id' => 2,
            'user_name' => 'testUser',
            'user_pass' => 'testPass',
            'email' => 'test@email.com',
        )),
    );

    protected $dataArray = array('user' => 'user', 'password' => 'password', 'email' => 'ebaa@eee.com');

    /**
     * @var Container
     */
    private $container;

    /**
     * @var Twig_Loader_Filesystem
     */
    private $twigLoader;

    public function setUp()
    {
        parent::setUp();
        global  $container;
        $this->container = $container;
        $this->twigLoader = $this->container->get(Twig_Loader_Filesystem::class);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $extraArray array
     *
     * @return RedBeanDB
     */
    private function getMockObject($extraArray = null)
    {
        $database = m::mock('MyPoll\Classes\Database\RedBeanDB');
        if ($extraArray) {
            foreach ($extraArray as $item) {
                $database->shouldReceive($item['method'])->once()->withAnyArgs()->andReturn($item['return']);
            }
        }
        return $database;
    }

    /**
     * @return Pagination
     */
    private function getMockPagination()
    {
        $pagination = m::mock('MyPoll\Classes\Pagination');
        $pagination->shouldReceive('setParams')->once()->withAnyArgs()->andReturn(true);
        $pagination->shouldReceive('getResults')->once()->withAnyArgs()->andReturn(true);
        $pagination->shouldReceive('getPagesNumber')->once()->withAnyArgs()->andReturn(true);
        return $pagination;
    }

    /**
     * @param array $extraArrayDB
     *
     * @return Users
     */
    private function getUsers($extraArrayDB = null)
    {
        $users =  new Users(
            $this->getMockObject($extraArrayDB),
            $this->container->get(Twig_Environment::class),
            $this->getMockPagination(),
            $this->container->get(Settings::class)
        );

        return $users;
    }

    public function testAddSuccess()
    {
        
        $this->assertContains('<input type="hidden" id="callBack" value="addExecute">', $this->getUsers()->add());
    }

    /**
     * @expectedException \Twig_Error_Loader
     */
    public function testAddFail()
    {
        $this->twigLoader->addPath('/wrongPath/');
        $this->getUsers()->add();
    }

    public function testGetPostParamsForAddMethodSuccess()
    {
        $_POST['user_name'] = 'username';
        $_POST['user_password'] = 'password';
        $_POST['user_email'] = 'aaaa@aaa.com';
        $this->assertEquals(
            array('user' => $_POST['user_name'], 'password' => $_POST['user_password'], 'email' => $_POST['user_email']),
            $this->getUsers()->getPostParamsForAddMethod()
        );
    }

    /**
     * @expectedException \PHPUnit_Framework_Error_Notice
     */
    public function testGetPostParamsForAddMethodFailWithNoPostParams()
    {
        $this->getUsers()->getPostParamsForAddMethod();
    }

    public function testGetPostParamsForAddMethodFailWithEmptyPostParams()
    {
        $_POST['user_name'] = '';
        $_POST['user_password'] = '';
        $_POST['user_email'] = '';
        $this->assertArrayHasKey('user', $this->getUsers()->getPostParamsForAddMethod());
    }

    public function testAddExecuteSuccess()
    {
        $extraArray = array(
            array('method' => 'addRows', 'return' => true),
            array('method' => 'store', 'return' => true),
            // false here means that the data are not existed already in the database
            array('method' => 'find', 'return' => false)
        );

        $user = $this->getUsers($extraArray);
        $this->assertEquals('User Added successfully', $user->addExecute($this->dataArray));
    }

    /**
     * @expectedException \Exception
     * @expectedExceptionMessage Something went wrong while trying to add the user
     */
    public function testAddExecuteFailWithException()
    {
        $extraArray = array(
            array('method' => 'addRows', 'return' => true),
            array('method' => 'store', 'return' => array()),
            // false here means that the data are not existed already in the database
            array('method' => 'find', 'return' => false)
        );

        $this->getUsers($extraArray)->addExecute($this->dataArray);
    }

    public function testAddExecuteFailWithExistedEmailOrUser()
    {
        $extraArray = array(
            // true here means that the data are existed already in the database
            array('method' => 'find', 'return' => true)
        );

        $user = $this->getUsers($extraArray);

        $this->assertEquals(
            $user::USER_OR_EMAIL_EXIST,
            $user->addExecute($this->dataArray)
        );
    }

    public function testAddExecuteFailWithInvalidEmail()
    {
        $dataArray = array('user' => 'user', 'password' => 'password', 'email' => General::cleanInput('email', 'ebaa'));
        $user = $this->getUsers();

        $this->assertEquals(
            $user::INVALID_EMAIL,
            $user->addExecute($dataArray)
        );
    }

    public function testShowSuccess()
    {
        $extraArray = array(array('method' => 'count', 'return' => 10), array('method' => 'find', 'return' => true));
        
        $this->assertContains('<div class="inner" id="inner8">User Name</div>', $this->getUsers($extraArray)->show());
    }

    /**
     * @expectedException \Twig_Error_Loader
     */
    public function testShowFailWithTwig()
    {
        $this->twigLoader->addPath('/wrongPath/');
        $extraArray = array(array('method' => 'count', 'return' => 10), array('method' => 'find', 'return' => true));
        $this->assertContains('<div class="inner" id="inner8">User Name</div>', $this->getUsers($extraArray)->show());
    }

    public function testShowFailWithEmptyFindResult()
    {
        $extraArray = array(array('method' => 'count', 'return' => 10), array('method' => 'find', 'return' => array()));
        

        try {
            $this->getUsers($extraArray)->show();
        } catch (\Exception $e) {
            $this->assertEquals(
                'An error occurred while trying to fetch rows for Pagination',
                $e->getMessage()
            );
        }
    }

    public function testEditSuccess()
    {
        
        $this->assertContains(
            '<input type="hidden" id="route" value="users">',
            $this->getUsers($this->extraArrayFull)->edit(2)
        );
    }

    public function testEditFailWithEmptyUser()
    {
        $extraArrayFull = array(array('method' => 'getById', 'return' => array()));
        $this->assertEquals(
            '<meta http-equiv="refresh" content="2; url=index.php?do=show&route=users">The user is not exist in the system',
            $this->getUsers($extraArrayFull)->edit(2)
        );
    }

    public function testGetPostParamsForEditMethodSuccess()
    {
        $_POST['user_id'] = 1;
        $_POST['user_name'] = 'userName';
        $_POST['user_password'] = 'password';
        $_POST['user_email'] = 'email@email.com';
        $this->assertEquals(
            array(
                'id' => $_POST['user_id'],
                'user' => $_POST['user_name'],
                'password' => $_POST['user_password'],
                'email' => $_POST['user_email']
            ),
            $this->getUsers()->getPostParamsForEditMethod()
        );
    }

    /**
     * @expectedException \PHPUnit_Framework_Error_Notice
     */
    public function testGetPostParamsForEditMethodFailWithNoPostParams()
    {
        $this->getUsers()->getPostParamsForEditMethod();
    }

    public function testGetPostParamsForEditMethodFailWithEmptyPostParams()
    {
        $_POST['user_id'] = '';
        $_POST['user_name'] = '';
        $_POST['user_password'] = '';
        $_POST['user_email'] = '';

        $this->assertEquals(
            array(
                'id' => '',
                'user' => '',
                'password' => false,
                'email' => '',
            ),
            $this->getUsers()->getPostParamsForEditMethod()
        );
    }

    public function testEditExecuteSuccess()
    {
        $dataArrayEdit = array(
        'id' => 2,
        'user' => 'testUser',
        'password' => 'testPass',
        'email' => 'test@email.com'
        );

        $extraArray = array(
            array('method' => 'find', 'return' => false),
            array('method' => 'getById', 'return' => true),
            array('method' => 'editRow', 'return' => true),
            array('method' => 'editRow', 'return' => true),
            array('method' => 'store', 'return' => true)
        );

        $user = $this->getUsers($extraArray);
        $this->assertEquals('User edited successfully', $user->editExecute($dataArrayEdit));
    }

    public function testEditExecuteSuccessWithEmptyPassword()
    {
        $dataArrayEdit = array(
            'id' => 2,
            'user' => 'testUser',
            'password' => '',
            'email' => 'test@email.com'
        );

        $extraArray = array(
            array('method' => 'find', 'return' => false),
            array('method' => 'getById', 'return' => true),
            array('method' => 'editRow', 'return' => true),
            array('method' => 'editRow', 'return' => true),
            array('method' => 'store', 'return' => true)
        );

        $user = $this->getUsers($extraArray);
        $this->assertEquals('User edited successfully', $user->editExecute($dataArrayEdit));
    }

    /**
     * @expectedException \Exception
     * @expectedExceptionMessage Something went wrong while trying to edit the user
     */
    public function testEditExecuteFailWithException()
    {
        $dataArrayEdit = array(
            'id' => 2,
            'user' => 'testUser',
            'password' => 'testPass',
            'email' => 'test@email.com'
        );

        $extraArray = array(
            array('method' => 'find', 'return' => false),
            array('method' => 'getById', 'return' => true),
            array('method' => 'editRow', 'return' => true),
            array('method' => 'editRow', 'return' => true),
            array('method' => 'store', 'return' => false)
        );

        $this->getUsers($extraArray)->editExecute($dataArrayEdit);
    }

    public function testEditExecuteFailWithExistedEmailOrUser()
    {
        $dataArrayEdit = array(
            'id' => 2,
            'user' => 'testUser',
            'password' => 'testPass',
            'email' => General::cleanInput('email', 'test@ddd.com')
        );

        $extraArray = array(
            // true here means that the data are existed already in the database
            array('method' => 'find', 'return' => true)
        );

        $user = $this->getUsers($extraArray);

        $this->assertEquals(
            $user::USER_OR_EMAIL_EXIST,
            $user->editExecute($dataArrayEdit)
        );
    }

    public function testEditExecuteFailWithInvalidEmail()
    {
        $dataArrayEdit = array(
            'id' => 2,
            'user' => 'testUser',
            'password' => 'testPass',
            'email' => General::cleanInput('email', 'test@')
        );

        $user = $this->getUsers();
        $this->assertEquals($user::INVALID_EMAIL, $user->editExecute($dataArrayEdit));
    }

    public function testDeleteSuccess()
    {
        $extraArray = array(
            array('method' => 'deleteById', 'return' => true)
        );
        $id = 2;
        $msg = 'The user with the ID ' . $id . ' has been deleted successfully';
        $url = 'index.php?do=show&route=users';
        $this->assertEquals(
            '<meta http-equiv="refresh" content="2; url=' . $url . '">' . $msg,
            $this->getUsers($extraArray)->delete($id)
        );
    }

    public function testDeleteFailWithAdminID()
    {
        $extraArray = array(
            array('method' => 'deleteById', 'return' => true)
        );
        $id = 1;
        $msg = 'Admin user could not be deleted';
        $url = 'index.php?do=show&route=users';
        $this->assertEquals(
            '<meta http-equiv="refresh" content="2; url=' . $url . '">' . $msg,
            $this->getUsers($extraArray)->delete($id)
        );
    }

    public function testGetHashSuccess()
    {
        $extraArray = array(
            array('method' => 'findOne', 'return' => array('user_pass' => 'hashedPass'))
        );

        $this->assertEquals(
            'hashedPass',
            $this->getUsers($extraArray)->getHash('user')
        );
    }

    public function testGetHashFailNoResultFound()
    {
        $extraArray = array(
            array('method' => 'findOne', 'return' => array())
        );

        $this->assertFalse($this->getUsers($extraArray)->getHash('user'));
    }
}
